sonar.projectKey=tinuvi_inertia-django-full-of-juice
sonar.organization=tinuvi

sonar.language=py
sonar.python.version=3.14

sonar.sources=inertia
sonar.tests=inertia/tests
sonar.exclusions=inertia/tests/**
sonar.coverage.exclusions=inertia/tests/**

sonar.python.xunit.reportPath=tests-reports/junit.xml
sonar.python.coverage.reportPaths=tests-reports/coverage.xml

sonar.verbose=false
